const DATE = 'DATE';

const SCORE = 'SCORE';
const MEMBERS = 'MEMBERS';
module.exports = {
  FIELD_MAX_LENGTH: 12,
  SEPARATOR: ' | ',
  WAR_FIXED_FIELDS: [ DATE, SCORE, 'ENEMY SCORE', 'BONUS', MEMBERS ],
  TITAN_FIXED_FIELDS: [ DATE, SCORE, 'LIFE', 'STARS', 'COLOR', MEMBERS ],
};
